gitignore: don't ignore *.i files
* Breaks the compilation if fw_sample.i doesn't exist under techpack

>>>
../techpack/xiaomi-sdm439/touchscreen/FT8006S/focaltech_config.h:235:50: fatal error: include/firmware/fw_sample.i: No such file or directory
  235 | #define FTS_UPGRADE_FW_FILE                      "include/firmware/fw_sample.i"
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
<<<

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>